# Generated by Django 2.1 on 2018-09-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_tag',
            fields=[
                ('tagName', models.CharField(default='missing_tag', max_length=64, primary_key=True, serialize=False)),
            ],
        ),
    ]
