# Generated by Django 2.1 on 2018-09-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_question',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
