# Generated by Django 2.1 on 2018-09-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_quiz_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_source',
            fields=[
                ('sourceName', models.CharField(default='missing source', max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='quiz_tag',
            name='tagName',
            field=models.CharField(default='missing tag', max_length=64, primary_key=True, serialize=False),
        ),
    ]
