# Generated by Django 2.1 on 2018-09-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_quiz_source_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_question',
            name='questionTags',
            field=models.ManyToManyField(to='Quiz.Quiz_tag'),
        ),
    ]
