# Generated by Django 2.1 on 2018-09-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_quiz_question_questiontags'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_question',
            name='questionSource',
            field=models.ManyToManyField(to='Quiz.Quiz_source'),
        ),
    ]
