# Generated by Django 2.1 on 2018-09-20 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_quiz_question_questionsource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_question',
            name='questionTags',
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='questionTags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quiz.Quiz_tag'),
        ),
    ]
