# Generated by Django 2.1 on 2018-09-20 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_auto_20180920_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_question',
            name='questionSource',
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='questionSource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionSource', to='Quiz.Quiz_tag'),
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='questionTags',
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='questionTags',
            field=models.ManyToManyField(to='Quiz.Quiz_tag'),
        ),
    ]
