# Generated by Django 2.1 on 2018-09-20 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_quiz_question_questionsolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerIsValid', models.BooleanField(default=False)),
                ('answerText', models.TextField(default='Missing answer text', max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='questionComments',
            field=models.TextField(default='Missing context', max_length=1024),
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='questionContent',
            field=models.TextField(default='Missing context', max_length=512),
        ),
        migrations.AddField(
            model_name='quiz_answer',
            name='parentQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Quiz_question'),
        ),
    ]
