# Generated by Django 2.1 on 2018-09-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0011_auto_20180920_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_question',
            name='questionContent',
            field=models.TextField(default='Missing context', max_length=1024),
        ),
    ]
