# Generated by Django 2.1 on 2018-09-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0012_auto_20180920_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_answer',
            name='id',
        ),
        migrations.AddField(
            model_name='quiz_answer',
            name='answerId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
