# Generated by Django 2.1 on 2018-09-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0014_auto_20180921_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quiz_answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quiz_question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quiz_question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
